name: go version1
on:
 workflow_dispatch:
   inputs:
     Goversion:
       description: 'Go version'
       required: true
       default: 'go1.19.3'
       type: choice
       options:
       - go1.19.5
       - go1.19.3
       - go1.18.1
      
job:
  log-the-inputs:
    run-on: ubuntu-latest
    steps:
      - run:
     echo "Go version: $GOVERSION"
     env: GOVERSION ${{inputs.Goversion}}     
