name: go-version
on:
 workflow_dispatch:
   inputs:
     Goversion:
       description: 'Goversion'
       required: true
       default: '1.15.15'
       type: choice
       options:
       - 1.16.6
       - 1.15.15
       - 1.12.4
      
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps: 
     - uses: actions/checkout@v3

     - name: Set up go
       uses: actions/setup-go@v3
       with:
         go-version: ${{ inputs.Goversion }}

     - name: Build
       run:  go build -v ./...

     - name: Test
       run:  go test -v ./...
       