name: go-version
on:
 workflow_dispatch:
   inputs:
     Goversion:
       description: 'Goversion'
       required: true
       default: '1.15.15'
       type: choice
       options:
       - 1.16.6
       - 1.15.15
       - 1.12.4
      
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Goversion: $GOVERSION"
        env:
          GOVERSION: ${{ inputs.Goversion }}     
