name: go-version1

on:

 workflow_dispatch:
   inputs:
     Goversion:
       description: 'Go-version'
       required: true
       default: '1.15'
       type: choice
       options:
       - 1.16
       - 1.15
       - 1.18

job:
  log-the-inputs:
    run-on: ubuntu-latest
    steps:
      - run:
        echo "Go version: $GOVERSION"
        env: GOVERSION ${{inputs.Goversion}}     

name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
